export const SET_CURRENCY = "SET_CURRENCY";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const SET_PLAN = "SET_PLAN";
export const RESET_CHECKOUT_STATE = "RESET_CHECKOUT_STATE";
